function [tab] = createGeoStatStruct(sed, UC, MC, LC, LM, ocean, mantle, bse, m1, m2, final_cut,...
    cc, crust, sed_sums, UC_cc_sums, MC_cc_sums, LC_cc_sums, LM_cc_sums, sed_oc_sums, ocean_sums,...
    man_sums_dm, man_sums_em, bse_sums, crust_sums,K)
%UNTITLED8 Summary of this function goes here
%   Detailed explanation goes here
% - Density (rho; g/cm3) (use 'find' to only get non-zero values as to not mess up stats)
    x = [stat(sed.rho(find(sed.rho)),m2);...
         stat(UC.rho(cc),m2);...
         stat(MC.rho(cc),m2);...
         stat(LC.rho(cc),m2);...
         stat(crust.rho,m2);...
         stat(LM.rho(cc),m2);...
         stat(sed.oc.rho(find(sed.oc.rho)),m2);...
         stat(ocean.rho,m2);...
         stat(mantle.dm.rho,m2);...
         stat(mantle.em.rho,m2);...
         stat(bse.rho,m2)]/1000; %(g/cm3) 
    tab.geo.rho = x; 

% - Thickness (km) (use 'find' to only get non-zero values as to not mess up stats)
    x = [stat(sed.thick(find(sed.thick)),m2);... % why is this producing NaN
        stat(UC.thick(cc),m2);...
        stat(MC.thick(cc),m2);...
        stat(LC.thick(cc),m2);...
        stat(crust.thick,m2);...
        stat(LM.thick(cc),m2);...
        stat(sed.oc.rho,m2);...
        stat(ocean.thick,m2);...
        stat(mantle.dm.thick(cc),m2)*1000;...
        stat(mantle.em.thick,m2)*1000;...
        stat(bse.thick,m2)*1000]/1000; %(km)
    tab.geo.thick = x; 

% - Mass (10^21 kg)
    x = [stat(sed_sums(final_cut,1),m2);...
        stat(UC_cc_sums(final_cut,1),m2);...
        stat(MC_cc_sums(final_cut,1),m2);...
        stat(LC_cc_sums(final_cut,1),m2);...
        stat(crust_sums(final_cut,1),m2);...
        stat(LM_cc_sums(final_cut,1),m2);...
        stat(sed_oc_sums(final_cut,1),m2);...
        stat(ocean_sums(final_cut,1),m2);...
        stat(man_sums_dm(final_cut,1),m2);...
        stat(man_sums_em(final_cut,1),m2);...
        stat(bse_sums(final_cut,1),m2)]/10^21; %(10^21 kg)
    tab.geo.mass.mass = x; 

% - Abundance of U (ppm; ug/g)
    x = [stat(sed_sums(final_cut,2)./sed_sums(final_cut,1),m2);...
        stat(UC_cc_sums(final_cut,2)./UC_cc_sums(final_cut,1),m2);...

        stat(MC_cc_sums(final_cut,2)./MC_cc_sums(final_cut,1),m1);...
        stat(LC_cc_sums(final_cut,2)./LC_cc_sums(final_cut,1),m1);...
        stat(crust_sums(final_cut,2)./crust_sums(final_cut,1),m1);...
        stat(LM_cc_sums(final_cut,2)./LM_cc_sums(final_cut,1),m1);...

        stat(sed_oc_sums(final_cut,2)./sed_oc_sums(final_cut,1),m2);...
        stat(ocean_sums(final_cut,2)./ocean_sums(final_cut,1),m2);...
        stat(man_sums_dm(final_cut,2)./man_sums_dm(final_cut,1),m2);...
        stat(man_sums_em(final_cut,2)./man_sums_em(final_cut,1),m2);...
        stat(bse_sums(final_cut,2)./bse_sums(final_cut,1),m2)]*10^6; %(ppm)
    tab.geo.abund.U = x;    

    
% - Abundance of Th (ppm; ug/g)
    x = [stat(sed_sums(final_cut,3)./sed_sums(final_cut,1),m2);...
        stat(UC_cc_sums(final_cut,3)./UC_cc_sums(final_cut,1),m2);...

        stat(MC_cc_sums(final_cut,3)./MC_cc_sums(final_cut,1),m1);...
        stat(LC_cc_sums(final_cut,3)./LC_cc_sums(final_cut,1),m1);...
        stat(crust_sums(final_cut,3)./crust_sums(final_cut,1),m1);...
        stat(LM_cc_sums(final_cut,3)./LM_cc_sums(final_cut,1),m1);...

        stat(sed_oc_sums(final_cut,3)./sed_oc_sums(final_cut,1),m2);...
        stat(ocean_sums(final_cut,3)./ocean_sums(final_cut,1),m2);...
        stat(man_sums_dm(final_cut,3)./man_sums_dm(final_cut,1),m2);...
        stat(man_sums_em(final_cut,3)./man_sums_em(final_cut,1),m2);...
        stat(bse_sums(final_cut,3)./bse_sums(final_cut,1),m2)]*10^6; %(ppm)
    tab.geo.abund.Th = x;   

% - Abundance of K (wt%)
    x = [stat(sed_sums(final_cut,4)./sed_sums(final_cut,1),m2);...
        stat(UC_cc_sums(final_cut,4)./UC_cc_sums(final_cut,1),m2);...

        stat(MC_cc_sums(final_cut,4)./MC_cc_sums(final_cut,1),m1);...
        stat(LC_cc_sums(final_cut,4)./LC_cc_sums(final_cut,1),m1);...
        stat(crust_sums(final_cut,4)./crust_sums(final_cut,1),m1);...
        stat(LM_cc_sums(final_cut,4)./LM_cc_sums(final_cut,1),m1);...

        stat(sed_oc_sums(final_cut,4)./sed_oc_sums(final_cut,1),m2);...
        stat(ocean_sums(final_cut,4)./ocean_sums(final_cut,1),m2);...
        stat(man_sums_dm(final_cut,4)./man_sums_dm(final_cut,1),m2);...
        stat(man_sums_em(final_cut,4)./man_sums_em(final_cut,1),m2);...
        stat(bse_sums(final_cut,4)./bse_sums(final_cut,1),m2)]*10^6; %(ppm)
    tab.geo.abund.K = x;   
    
% - Mass of U (10^15 kg)
    x = [stat(sed_sums(final_cut,2),m2);...
        stat(UC_cc_sums(final_cut,2),m2);...

        stat(MC_cc_sums(final_cut,2),m1);...
        stat(LC_cc_sums(final_cut,2),m1);...
        stat(crust_sums(final_cut,2),m1);...
        stat(LM_cc_sums(final_cut,2),m1);...

        stat(sed_oc_sums(final_cut,2),m2);...
        stat(ocean_sums(final_cut,2),m2);...
        stat(man_sums_dm(final_cut,2),m2);...
        stat(man_sums_em(final_cut,2),m2);...
        stat(bse_sums(final_cut,2),m2)]/10^15; %(10^15 kg)
    tab.geo.mass.U = x; 
    
% - Mass of Th (10^15 kg)
    x = [stat(sed_sums(final_cut,3),m2);...
        stat(UC_cc_sums(final_cut,3),m2);...

        stat(MC_cc_sums(final_cut,3),m1);...
        stat(LC_cc_sums(final_cut,3),m1);...
        stat(crust_sums(final_cut,3),m1);...
        stat(LM_cc_sums(final_cut,3),m1);...

        stat(sed_oc_sums(final_cut,3),m2);...
        stat(ocean_sums(final_cut,3),m2);...
        stat(man_sums_dm(final_cut,3),m2);...
        stat(man_sums_em(final_cut,3),m2);...

        stat(bse_sums(final_cut,3),m2)]/10^15; %(10^15 kg)
    tab.geo.mass.Th = x; 

% - Mass of K (10^19 kg)
    x = [stat(sed_sums(final_cut,4),m2);...
        stat(UC_cc_sums(final_cut,4),m2);...

        stat(MC_cc_sums(final_cut,4),m1);...
        stat(LC_cc_sums(final_cut,4),m1);...
        stat(crust_sums(final_cut,4),m1);...
        stat(LM_cc_sums(final_cut,4),m1);...

        stat(sed_oc_sums(final_cut,4),m2);...
        stat(ocean_sums(final_cut,4),m2);...
        stat(man_sums_dm(final_cut,4),m2);...
        stat(man_sums_em(final_cut,4),m2);...
        stat(bse_sums(final_cut,4),m2)]/10^19/K.b; %(10^19 kg)
    tab.geo.mass.K = x; 

% - Heat production (TW; 10^12 W)
      x = [stat(sed_sums(final_cut,6),m2);...
        stat(UC_cc_sums(final_cut,6),m2);...

        stat(MC_cc_sums(final_cut,6),m1);...
        stat(LC_cc_sums(final_cut,6),m1);...
        stat(crust_sums(final_cut,6),m1);...
        stat(LM_cc_sums(final_cut,6),m1);...

        stat(sed_oc_sums(final_cut,6),m2);...
        stat(ocean_sums(final_cut,6),m2);...
        stat(man_sums_dm(final_cut,6),m2);...
        stat(man_sums_em(final_cut,6),m2);...
        stat(bse_sums(final_cut,6),m2)]/10^12; %(10^12 W (TW))
    tab.geo.hp = x;
end